# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for hex
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for crates
  - package-ecosystem: "cargo"
    directory: "/native/mjml_nif"
    schedule:
      interval: "daily"
