[package]
name = "mjml_nif"
version = "1.1.3"
authors = ["Paul Götze"]
edition = "2018"

[lib]
name = "mjml_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
mrml = { version = "1.2", default-features = false, features = ["parse", "render"] }
